server:
  port: 8761

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
  server:
    waitTimeInMsWhenSyncEmpty: 0
logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF
  file:
    path: /var/logs/
